/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author cikaandhini
 */
public class Praktikum2 extends javax.swing.JFrame {

    /**
     * Creates new form Praktikum2
     */
    public Praktikum2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jconhari = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jtxtsayur1 = new javax.swing.JTextField();
        jtxtsayur2 = new javax.swing.JTextField();
        jtxtsayur3 = new javax.swing.JTextField();
        jtxtsayur4 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jtxtlauk1 = new javax.swing.JTextField();
        jtxtlauk2 = new javax.swing.JTextField();
        jtxtlauk3 = new javax.swing.JTextField();
        jtxtlauk4 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jtxtlauktam1 = new javax.swing.JTextField();
        jtxtlauktam2 = new javax.swing.JTextField();
        jtxtlauktam3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Daftar Makanan Cathering \"YULI\"");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 20, 410, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nama Makanan");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 90, 110, 30);

        jconhari.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jconhari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih hari cathering --", "Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu", " " }));
        jconhari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jconhariActionPerformed(evt);
            }
        });
        getContentPane().add(jconhari);
        jconhari.setBounds(200, 90, 190, 30);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sayur", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel1.setLayout(null);

        jtxtsayur1.setEditable(false);
        jPanel1.add(jtxtsayur1);
        jtxtsayur1.setBounds(20, 30, 220, 30);

        jtxtsayur2.setEditable(false);
        jPanel1.add(jtxtsayur2);
        jtxtsayur2.setBounds(20, 70, 220, 30);

        jtxtsayur3.setEditable(false);
        jPanel1.add(jtxtsayur3);
        jtxtsayur3.setBounds(20, 110, 220, 30);

        jtxtsayur4.setEditable(false);
        jPanel1.add(jtxtsayur4);
        jtxtsayur4.setBounds(20, 150, 220, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 150, 260, 200);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lauk Pauk", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel2.setLayout(null);

        jtxtlauk1.setEditable(false);
        jPanel2.add(jtxtlauk1);
        jtxtlauk1.setBounds(20, 30, 220, 30);

        jtxtlauk2.setEditable(false);
        jPanel2.add(jtxtlauk2);
        jtxtlauk2.setBounds(20, 70, 220, 30);

        jtxtlauk3.setEditable(false);
        jPanel2.add(jtxtlauk3);
        jtxtlauk3.setBounds(20, 110, 220, 30);

        jtxtlauk4.setEditable(false);
        jPanel2.add(jtxtlauk4);
        jtxtlauk4.setBounds(20, 150, 220, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(300, 150, 260, 200);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lauk tambahan ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel3.setLayout(null);

        jtxtlauktam1.setEditable(false);
        jPanel3.add(jtxtlauktam1);
        jtxtlauktam1.setBounds(30, 30, 200, 30);

        jtxtlauktam2.setEditable(false);
        jPanel3.add(jtxtlauktam2);
        jtxtlauktam2.setBounds(30, 70, 200, 30);

        jtxtlauktam3.setEditable(false);
        jPanel3.add(jtxtlauktam3);
        jtxtlauktam3.setBounds(30, 110, 200, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(160, 370, 250, 150);

        jLabel3.setText("NB : Hari Minggu dan Hari Besar tutup");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 540, 190, 14);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("HUB : 085331727667");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(410, 540, 160, 17);

        setBounds(0, 0, 600, 604);
    }// </editor-fold>//GEN-END:initComponents

    private void jconhariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jconhariActionPerformed
        if(jconhari.getSelectedItem().equals("Senin")){
            jtxtsayur1.setText("Sayur Bayam");
            jtxtsayur2.setText("Sayur Sop");
            jtxtsayur3.setText("Sayur Lodeh");
            jtxtsayur4.setText("Capcay");
            jtxtlauk1.setText("Ikan Bandeng");
            jtxtlauk2.setText("Ikan Mujair");
            jtxtlauk3.setText("Tempe goreng");
            jtxtlauk4.setText("Ayam goreng");
            jtxtlauktam1.setText("Nugget");
            jtxtlauktam2.setText("Rolade");
            jtxtlauktam3.setText("Perkedel");
        }else
        if (jconhari.getSelectedItem().equals("Selasa")) {
            jtxtsayur1.setText("Cah Kangkung");
            jtxtsayur2.setText("Capcay Kering");
            jtxtsayur3.setText("Cah Sawi");
            jtxtsayur4.setText("Oseng-oseng Kacang");
            jtxtlauk1.setText("Cumi-cumi");
            jtxtlauk2.setText("Tempe Goreng");
            jtxtlauk3.setText("Tahu Bulat");
            jtxtlauk4.setText("Ayam Kremes");
            jtxtlauktam1.setText("Nugget");
            jtxtlauktam2.setText("Rolade");
            jtxtlauktam3.setText("Sosis");
            }else
        if (jconhari.getSelectedItem().equals("Rabu")) {
            jtxtsayur1.setText("Kering Tempe");
            jtxtsayur2.setText("Oseng-oseng Tempe");
            jtxtsayur3.setText("Sop Ayam");
            jtxtsayur4.setText("Rica-rica buncis");
            jtxtlauk1.setText("Sardine");
            jtxtlauk2.setText("Tahu kuning goreng");
            jtxtlauk3.setText("Ayam suwir");
            jtxtlauk4.setText("Otak-otak");
            jtxtlauktam1.setText("Nugget");
            jtxtlauktam2.setText("Bakso");
            jtxtlauktam3.setText("Sosis");
            }else
        if (jconhari.getSelectedItem().equals("Kamis")) {
            jtxtsayur1.setText("Cah Sawi");
            jtxtsayur2.setText("Capcay");
            jtxtsayur3.setText("Sop Ayam");
            jtxtsayur4.setText("Bakmi");
            jtxtlauk1.setText("Ikan Lele");
            jtxtlauk2.setText("Tahu tempe goreng");
            jtxtlauk3.setText("Kulit ayam goreng");
            jtxtlauk4.setText("Cumi goreng");
            jtxtlauktam1.setText("Sosis");
            jtxtlauktam2.setText("Nugget");
            jtxtlauktam3.setText("Bakso");
            }else
        if (jconhari.getSelectedItem().equals("Jumat")) {
            jtxtsayur1.setText("Sayur Lodeh");
            jtxtsayur2.setText("Sayur Krecek");
            jtxtsayur3.setText("Cah Sawi");
            jtxtsayur4.setText("Oseng-oseng Kacang");
            jtxtlauk1.setText("Cumi-cumi");
            jtxtlauk2.setText("Ayam goreng tepung");
            jtxtlauk3.setText("Chicken Katsu");
            jtxtlauk4.setText("Koloke");
            jtxtlauktam1.setText("Bakso");
            jtxtlauktam2.setText("Rolade");
            jtxtlauktam3.setText("Sosis");
            }else
        if (jconhari.getSelectedItem().equals("Sabtu")) {
            jtxtsayur1.setText("Sop sapi");
            jtxtsayur2.setText("Capcay Kering");
            jtxtsayur3.setText("Rica-rica Buncis");
            jtxtsayur4.setText("Oseng-oseng Kacang+tempe");
            jtxtlauk1.setText("Cumi goreng");
            jtxtlauk2.setText("Ikan Goreng");
            jtxtlauk3.setText("Ikan Lele");
            jtxtlauk4.setText("Koloke");
            jtxtlauktam1.setText("Bakso Ikan");
            jtxtlauktam2.setText("Perkedel");
            jtxtlauktam3.setText("Sosis");
            }
    }//GEN-LAST:event_jconhariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Praktikum2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Praktikum2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Praktikum2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Praktikum2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Praktikum2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JComboBox<String> jconhari;
    private javax.swing.JTextField jtxtlauk1;
    private javax.swing.JTextField jtxtlauk2;
    private javax.swing.JTextField jtxtlauk3;
    private javax.swing.JTextField jtxtlauk4;
    private javax.swing.JTextField jtxtlauktam1;
    private javax.swing.JTextField jtxtlauktam2;
    private javax.swing.JTextField jtxtlauktam3;
    private javax.swing.JTextField jtxtsayur1;
    private javax.swing.JTextField jtxtsayur2;
    private javax.swing.JTextField jtxtsayur3;
    private javax.swing.JTextField jtxtsayur4;
    // End of variables declaration//GEN-END:variables
}
